// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HowdahSession struct {
	ID                []byte
	Subject           string
	KeyID             []byte
	Payload           []byte
	AccessExpiresAt   pgtype.Timestamptz
	RefreshLeaseUntil pgtype.Timestamptz
	RefreshLeaseNonce []byte
	RefreshFailedAt   pgtype.Timestamptz
	RefreshedAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
}
