// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitRefresh = `-- name: CommitRefresh :execrows
UPDATE howdah_session
SET    payload = $1,
       key_id = $2,
       access_expires_at = $3,
       refreshed_at = now(),
       refresh_lease_until = NULL,
       refresh_lease_nonce = NULL,
       refresh_failed_at = NULL
WHERE  id = $4 AND refresh_lease_nonce = $5
`

type CommitRefreshParams struct {
	Payload         []byte
	KeyID           []byte
	AccessExpiresAt pgtype.Timestamptz
	ID              []byte
	Nonce           []byte
}

// Writes the result of a refresh back, fenced on the lease nonce. Without
// the fence a refresher whose exchange finished but whose write stalled past
// its lease could land on top of a fresher winner's tokens, leaving a
// rotated-away refresh token in the row and the session dead fleet-wide.
// Zero rows means the lease was lost: discard the result and re-read.
func (q *Queries) CommitRefresh(ctx context.Context, arg CommitRefreshParams) (int64, error) {
	result, err := q.db.Exec(ctx, commitRefresh,
		arg.Payload,
		arg.KeyID,
		arg.AccessExpiresAt,
		arg.ID,
		arg.Nonce,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSession = `-- name: CreateSession :one
INSERT INTO howdah_session(
  id, subject, key_id, payload, access_expires_at,
  refreshed_at, created_at, expires_at
) VALUES (
  $1, $2, $3, $4, $5,
  now(), now(), now() + $6::interval
)
RETURNING created_at, expires_at
`

type CreateSessionParams struct {
	ID              []byte
	Subject         string
	KeyID           []byte
	Payload         []byte
	AccessExpiresAt pgtype.Timestamptz
	MaxSessionAge   pgtype.Interval
}

type CreateSessionRow struct {
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.Subject,
		arg.KeyID,
		arg.Payload,
		arg.AccessExpiresAt,
		arg.MaxSessionAge,
	)
	var i CreateSessionRow
	err := row.Scan(&i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM howdah_session
WHERE id IN (
  SELECT id FROM howdah_session
  WHERE expires_at <= now()
  LIMIT $1
)
`

// Deletes at most batch sessions that are past their absolute expiry. The
// subselect is what bounds the delete: an unbounded one takes a lock on
// every dead row in the table at once.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, batch int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM howdah_session WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSubjectSessions = `-- name: DeleteSubjectSessions :execrows
DELETE FROM howdah_session WHERE subject = $1
`

func (q *Queries) DeleteSubjectSessions(ctx context.Context, subject string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubjectSessions, subject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failRefresh = `-- name: FailRefresh :execrows
UPDATE howdah_session
SET    refresh_failed_at = now(),
       refresh_lease_until = NULL,
       refresh_lease_nonce = NULL
WHERE  id = $1 AND refresh_lease_nonce = $2
`

type FailRefreshParams struct {
	ID    []byte
	Nonce []byte
}

// Records that a refresh attempt failed and releases the lease, so that the
// callers waiting on it fail fast rather than polling a refreshed_at that
// will never move, burning their whole backoff and then each attempting an
// exchange of their own. Fenced on the nonce for the same reason the commit
// is.
func (q *Queries) FailRefresh(ctx context.Context, arg FailRefreshParams) (int64, error) {
	result, err := q.db.Exec(ctx, failRefresh, arg.ID, arg.Nonce)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSession = `-- name: GetSession :one
SELECT subject, key_id, payload, access_expires_at, refresh_lease_until,
       refresh_lease_nonce, refresh_failed_at, refreshed_at, created_at,
       expires_at, now()::timestamptz AS db_now
FROM howdah_session
WHERE id = $1
`

type GetSessionRow struct {
	Subject           string
	KeyID             []byte
	Payload           []byte
	AccessExpiresAt   pgtype.Timestamptz
	RefreshLeaseUntil pgtype.Timestamptz
	RefreshLeaseNonce []byte
	RefreshFailedAt   pgtype.Timestamptz
	RefreshedAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
	DbNow             pgtype.Timestamptz
}

func (q *Queries) GetSession(ctx context.Context, id []byte) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.Subject,
		&i.KeyID,
		&i.Payload,
		&i.AccessExpiresAt,
		&i.RefreshLeaseUntil,
		&i.RefreshLeaseNonce,
		&i.RefreshFailedAt,
		&i.RefreshedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DbNow,
	)
	return i, err
}

const listRekeySessions = `-- name: ListRekeySessions :many
SELECT id, key_id, payload, refreshed_at
FROM   howdah_session
WHERE  key_id <> $1 AND expires_at > now()
ORDER BY id
LIMIT  $2
`

type ListRekeySessionsParams struct {
	KeyID []byte
	Batch int32
}

type ListRekeySessionsRow struct {
	ID          []byte
	KeyID       []byte
	Payload     []byte
	RefreshedAt pgtype.Timestamptz
}

// Finds the live sessions sealed under some other key than the one we seal
// with now, through the key_id index rather than by opening every row.
func (q *Queries) ListRekeySessions(ctx context.Context, arg ListRekeySessionsParams) ([]ListRekeySessionsRow, error) {
	rows, err := q.db.Query(ctx, listRekeySessions, arg.KeyID, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRekeySessionsRow
	for rows.Next() {
		var i ListRekeySessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyID,
			&i.Payload,
			&i.RefreshedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resealSession = `-- name: ResealSession :execrows
UPDATE howdah_session
SET    key_id = $1,
       payload = $2
WHERE  id = $3
  AND  key_id = $4
  AND  refreshed_at = $5
`

type ResealSessionParams struct {
	KeyID           []byte
	Payload         []byte
	ID              []byte
	SeenKeyID       []byte
	SeenRefreshedAt pgtype.Timestamptz
}

// Re-seals one row's payload, fenced on both the key id and the refreshed_at
// the sweep read. Without both, a sweep that interleaves with a refresh
// commits a re-sealed copy of the old payload over the new one — which, with
// refresh token rotation on, resurrects a token the provider has revoked and
// kills the session.
func (q *Queries) ResealSession(ctx context.Context, arg ResealSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, resealSession,
		arg.KeyID,
		arg.Payload,
		arg.ID,
		arg.SeenKeyID,
		arg.SeenRefreshedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeRefreshLease = `-- name: TakeRefreshLease :one
UPDATE howdah_session
SET    refresh_lease_until = now() + $1::interval,
       refresh_lease_nonce = $2
WHERE  id = $3
  AND  (refresh_lease_until IS NULL OR refresh_lease_until < now())
  AND  refreshed_at <= $4
  AND  refresh_failed_at IS NOT DISTINCT FROM $5
  AND  expires_at > now()
RETURNING subject, key_id, payload, refreshed_at, created_at, expires_at
`

type TakeRefreshLeaseParams struct {
	Lease           pgtype.Interval
	Nonce           []byte
	ID              []byte
	SeenRefreshedAt pgtype.Timestamptz
	SeenFailedAt    pgtype.Timestamptz
}

type TakeRefreshLeaseRow struct {
	Subject     string
	KeyID       []byte
	Payload     []byte
	RefreshedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

// Takes the refresh lease. It is a conditional UPDATE rather than a
// SELECT ... FOR UPDATE or an advisory lock, because either of those holds a
// pooled connection open across an HTTP round trip to the identity provider:
// a hung provider then drains the pool and takes down the whole application
// rather than just its logins. The lease holds no transaction — take it,
// commit, do the round trip, commit the result.
//
// The refreshed_at clause is the idempotency guard. If somebody refreshed
// between the caller's read and this attempt, refreshed_at has moved past
// what the caller saw, no row comes back, and the caller re-reads instead of
// refreshing a token that is already fresh.
//
// The refresh_failed_at clause closes the same window on the failure side.
// A refresher that fails releases the lease and sets the marker in one
// statement, so a caller that read the row before that and asks for the
// lease after it would otherwise find the lease free and exchange the same
// refresh token again — which is exactly the n-attempts-per-outage the
// marker exists to prevent.
func (q *Queries) TakeRefreshLease(ctx context.Context, arg TakeRefreshLeaseParams) (TakeRefreshLeaseRow, error) {
	row := q.db.QueryRow(ctx, takeRefreshLease,
		arg.Lease,
		arg.Nonce,
		arg.ID,
		arg.SeenRefreshedAt,
		arg.SeenFailedAt,
	)
	var i TakeRefreshLeaseRow
	err := row.Scan(
		&i.Subject,
		&i.KeyID,
		&i.Payload,
		&i.RefreshedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :execrows
UPDATE howdah_session
SET    key_id = $1,
       payload = $2,
       access_expires_at = $3,
       refreshed_at = now(),
       refresh_lease_until = NULL,
       refresh_lease_nonce = NULL,
       refresh_failed_at = NULL
WHERE  id = $4
`

type UpdateSessionParams struct {
	KeyID           []byte
	Payload         []byte
	AccessExpiresAt pgtype.Timestamptz
	ID              []byte
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSession,
		arg.KeyID,
		arg.Payload,
		arg.AccessExpiresAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
